---
language: node_js
node_js:
  - "4"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - TEST_SCRIPT=test:emberall

  # Run the node build tests only if we've modified a build file
  - TEST_SCRIPT=test:node:ci

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm run $TEST_SCRIPT
