---
language: node_js
node_js:
  - "4"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - TEST_SCRIPT=test:emberall
  - TEST_SCRIPT=test:node

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install -g npm # make sure npm is updated for ember-cli
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm run $TEST_SCRIPT
